### ISSUE TITLE
Needs to be completed

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/intro-to-tic-tac-toe-rb#1]
I'll do it. Deadline Thursday, 9/25/2015

**Comment by aviflombaum** [comment]
Done, @AnnJohn @matbalez want to look it over?

**Comment by AnnJohn** [comment]
Also assigned to @SophieDeBenedetto for review

Deadline: 10/2/2015

**Comment by AnnJohn** [comment]
I don't know if this isn't mentioned elsewhere, but in addition to letting students know that they're going to be building Tic Tac Toe, could be helpful to mention how the individual labs break this down (that can be as simple as replacing line 47 in the readme- "We'll break all these requirements down into simple procedures"- to "We'll We'll break all these requirements down into simple, cumulative labs throughout the track."

Could also be helpful to talk briefly about how the rest of the content in this track works to help you get the Tic Tac Toe labs done. That would address Mat's concern about the flow, and how the ttt labs feels thrown in there. 

@aviflombaum
